### ISSUE TITLE
api问题

### ISSUE THREAD

**Issue by wzhang12** [allwefantasy/ServiceFramework#43]
BootStrap.java中
Tuple<Settings, Environment> tuple = InternalSettingsPreparer.prepareSettings(EMPTY_SETTINGS, ServiceFramwork.applicaionYamlName());传了两个参数 但是csdn_common找不到啊

**Comment by allwefantasy** [comment]
```
git clone https://github.com/allwefantasy/csdn_common.git
cd csdn_common
mvn -DskipTests clean install
```
我没有及时提交，已经处理了。通过上面的方式获得最新版本。 应该就能解决了。
