### ISSUE TITLE
render总是返回{     "empty": false,     "traversableAgain": true }

### ISSUE THREAD

**Issue by Mvpanswer7** [allwefantasy/ServiceFramework#52]
我在用serviceframework写返回json的rest api时，总是遇到render(json/list)，结果返回一个{
    "empty": false,
    "traversableAgain": true
}
这个东西，请问这是什么意思啊？

**Comment by allwefantasy** [comment]
这个是因为你渲染的是scala的list。目前render 使用的json库是json-lib,所以建议你使用lift-web之类的库把scala 集合渲染成字符串后再调用render

**Comment by Mvpanswer7** [comment]
嗯，改用java的collection之后就没这个问题了
